#!/bin/sh
# Copyright 2023 David Farrell

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
num_workers=1
num_fifos=0
next_fifo=1
prefix_inp="${TMPDIR-/tmp}/forklift-$$"
prefix_sig="$prefix_inp-x"

cleanup() {
	for sigchan in "$prefix_sig"*; do
		echo 1 >"$sigchan"
	done
	rm -f "$prefix_inp"*
	wait
}
trap cleanup ABRT EXIT INT TERM

# tails until told to stop
tailsig() {
	inp="$1"
	sig="$2"
	tail -f "$inp" &
	childpid=$!
	read line <"$sig"
	kill "$childpid" >/dev/null 2>&1
}

# process args
while getopts "w:" opt; do
	case "$opt" in
	'w') num_workers="$OPTARG" ;;
	*)
		printf "Usage:\n\tforklift [-w#] command\n"
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))
if [ $# -ne 1 ]; then
	printf "Must provide 1 command.\nUsage:\n\tforklift [-w#] command\n"
	exit 1
fi

# create worker pool
while [ "$num_fifos" -lt "$num_workers" ]; do
	num_fifos=$((num_fifos + 1))
	mkfifo "$prefix_inp-$num_fifos"
	mkfifo "$prefix_sig-$num_fifos"
	tailsig "$prefix_inp-$num_fifos" "$prefix_sig-$num_fifos" | eval "$1" &
done

# distribute input
while read -r line; do
	echo "$line" >"$prefix_inp-$next_fifo"
	if [ "$next_fifo" -eq "$num_workers" ]; then
		next_fifo=1
	else
		next_fifo=$((next_fifo + 1))
	fi
done
